CREATE TABLE IF NOT EXISTS "UserRegistrationSurveys" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" integer NOT NULL,
    "PrimaryGoal" character varying(60) NOT NULL,
    "PlannedJobCount" character varying(60) NOT NULL,
    "SpendingHabit" character varying(60) NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "UpdatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "FK_UserRegistrationSurveys_Users_UserId"
        FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_UserRegistrationSurveys_UserId"
    ON "UserRegistrationSurveys" ("UserId");
