CREATE TABLE IF NOT EXISTS "PasswordResetTokens" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" integer NOT NULL,
    "CodeHash" character varying(128) NOT NULL,
    "ExpiresAt" timestamp without time zone NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL DEFAULT NOW(),
    "UsedAt" timestamp without time zone NULL,
    "FailedAttempts" integer NOT NULL DEFAULT 0,
    CONSTRAINT "FK_PasswordResetTokens_Users_UserId"
        FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_PasswordResetTokens_UserId"
    ON "PasswordResetTokens" ("UserId");

CREATE INDEX IF NOT EXISTS "IX_PasswordResetTokens_UserId_CreatedAt"
    ON "PasswordResetTokens" ("UserId", "CreatedAt");
